export class User {

    constructor(
        public userid?: number,  // will be autogenerated
        public username?: String,  // this is infact the email address user will enter on the website screen
        public name?: String,
        public location?: String,
        public password?: String,
        public role?: String,
        public education?: String
    ) { }

   
}